apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: csi-lvm
provisioner: local.csi.ecloud.cmss.com
parameters:
    vgName: volumegroup1
    fsType: ext4
    readIOPS: 2000
    writeIOPS: 1000
    readBPS: 10M
    writeBPS: 5M
reclaimPolicy: Delete
